# Generated by Django 4.2.9 on 2024-01-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Расходы:'),
        ),
    ]
