# Generated by Django 4.2.9 on 2024-01-23 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_wallet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_name',
        ),
    ]
