# Generated by Django 4.2.9 on 2024-01-27 08:51

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_wallet_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='revenues',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, validators=[users.validators.validate_positive], verbose_name='Доходы:'),
        ),
    ]
