# Generated by Django 4.2.9 on 2024-01-23 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_wallet_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Кошелёк', 'verbose_name_plural': 'Кошельки'},
        ),
    ]
