# Generated by Django 4.2.9 on 2024-01-27 16:01

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_wallet_expenses_alter_wallet_revenues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='revenues',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, null=True, validators=[users.validators.validate_positive], verbose_name='Доходы:'),
        ),
    ]
