# Generated by Django 4.2.9 on 2024-02-07 14:12

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_wallet_own'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='revenues',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, null=True, validators=[users.validators.validate_positive], verbose_name='Доход:'),
        ),
    ]
