# Generated by Django 4.2.9 on 2024-02-12 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_wallet_expenses_alter_wallet_revenues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='expenses',
        ),
    ]
