# Generated by Django 4.2.9 on 2024-02-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_wallet_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='users/default.png', null=True, upload_to='users/%Y/%m/%d/', verbose_name='Фотография'),
        ),
    ]
