# Generated by Django 4.2.9 on 2024-02-18 17:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название категории')),
                ('subcategory', models.CharField(choices=[('1', 'Потребности'), ('2', 'Развлечения'), ('3', 'Сбережения и инвестиции')], max_length=255, null=True, verbose_name='Подкатегория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категории',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=17, validators=[django.core.validators.MinValueValidator(0.0001, 'Сумма должна быть больше 0')], verbose_name='Сумма:')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Краткое описание:')),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rec', to='information.category', verbose_name='Категория:')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'ordering': ['-time_create'],
            },
        ),
    ]
