# Generated by Django 4.2.9 on 2024-01-26 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='records',
        ),
        migrations.AlterField(
            model_name='record',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rec', to='information.category', verbose_name='Записи'),
        ),
    ]
