# Generated by Django 4.2.9 on 2024-01-26 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0002_alter_record_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='buyer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buying', to=settings.AUTH_USER_MODEL, verbose_name='Владелец:'),
        ),
    ]
