# Generated by Django 4.2.9 on 2024-01-26 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_remove_category_records_alter_record_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='record',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rec', to='information.category', verbose_name='Категории'),
        ),
    ]
