# Generated by Django 4.2.9 on 2024-01-26 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_record_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='categories',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rec', to='information.category', verbose_name='Категория:'),
        ),
    ]
