# Generated by Django 4.2.9 on 2024-02-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_alter_record_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Сумма:'),
        ),
    ]
