# Generated by Django 4.2.9 on 2024-02-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_alter_record_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.CharField(max_length=255, null=True, verbose_name='Подкатегория'),
        ),
    ]
