# Generated by Django 4.2.9 on 2024-02-15 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0008_alter_category_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Время создания'),
        ),
    ]
